### ISSUE TITLE
fail: sql: expected 0 arguments, got 2

### ISSUE THREAD

**Issue by lxiangv** [Breeze0806/go-etl#36]
[config.json](https://github.com/Breeze0806/go-etl/files/15281749/config.json)

when I use this config file expecting to query data which id is between 1 and 9, it runs fail as the pic below

![image](https://github.com/Breeze0806/go-etl/assets/169515633/50e1de7a-dcae-41aa-933b-259fe640d570)

**Comment by Shane-XB-Qian** [comment]
the log seems was incomplete, the err looks was the query failed.

**Comment by Breeze0806** [comment]
The issue arises when trying to split a table into one part. In this case, the job.setting has not been set, and therefore the number of tables to split into is set to 1.

**Comment by Shane-XB-Qian** [comment]
that he/she pasted log was confused: `expected 0 arguments, got 2`, um...
my first feeling was: it was set to split 1~9, but actually there was nothing can be done for split?
so maybe if there had `where` clause would help?

**Comment by Breeze0806** [comment]
Haha, this is actually an issue caused by a misjudgment. Originally, my intention was that this judgment would speed up the program processing, but unfortunately, it resulted in this issue .



At 2024-05-13 22:41:02, "Shane-XB-Qian" ***@***.***> wrote:

that he/she pasted log was confused: expected 0 arguments, got 2, um...
my first feeling was: it was set to split 1~9, but actually there was nothing can be done for split?
so maybe if there had where clause would help?

**Comment by Breeze0806** [comment]
@lxiangv Thank you for your feedback, now you can try again.
